/**
 * PDF export — renders a report HTML page to PDF via Playwright.
 *
 * Uses the app's own public report page as the source HTML,
 * rendered headlessly with Playwright.
 */

import { chromium } from "playwright";

interface PdfOptions {
  reportUrl: string; // Full URL to the report page to render
}

/**
 * Generate a PDF buffer from a report page URL.
 */
export async function generatePdf(options: PdfOptions): Promise<Buffer> {
  const browser = await chromium.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const page = await browser.newPage();

    await page.goto(options.reportUrl, {
      waitUntil: "networkidle",
      timeout: 30000,
    });

    // Wait for charts to render
    await page.waitForTimeout(2000);

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size:8px; width:100%; text-align:center; color:#666;">
          Accessibility Compliance Report — Generated by EnableUser
        </div>
      `,
      footerTemplate: `
        <div style="font-size:8px; width:100%; text-align:center; color:#666;">
          Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>
      `,
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}

/**
 * Generate a PDF from raw HTML string (fallback for when no URL is available).
 */
export async function generatePdfFromHtml(html: string): Promise<Buffer> {
  const browser = await chromium.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });
    await page.waitForTimeout(1000);

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}
